// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Prompteer.Infrastructure.Data;

#nullable disable

namespace Prompteer.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260302111356_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Prompteer.Domain.Entities.AgentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultConstraints")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("KnowledgeDomain")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Tone")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("agent_profiles", (string)null);
                });

            modelBuilder.Entity("Prompteer.Domain.Entities.ArchitecturalPattern", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Ecosystem")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.ToTable("architectural_patterns", (string)null);
                });

            modelBuilder.Entity("Prompteer.Domain.Entities.BacklogTool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultInstructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("backlog_tools", (string)null);
                });

            modelBuilder.Entity("Prompteer.Domain.Entities.PromptDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentStep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WizardDataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("prompt_drafts", (string)null);
                });

            modelBuilder.Entity("Prompteer.Domain.Entities.PromptModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PromptTemplateVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PromptTemplateVersionId", "DisplayOrder");

                    b.ToTable("prompt_modules", (string)null);
                });

            modelBuilder.Entity("Prompteer.Domain.Entities.PromptModuleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("PromptModuleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PromptModuleId");

                    b.ToTable("prompt_module_items", (string)null);
                });

            modelBuilder.Entity("Prompteer.Domain.Entities.PromptTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentVersionNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted", "UpdatedAt");

                    b.ToTable("prompt_templates", (string)null);
                });

            modelBuilder.Entity("Prompteer.Domain.Entities.PromptTemplateVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeneratedPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PromptTemplateId")
                        .HasColumnType("uuid");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("WizardDataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PromptTemplateId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("prompt_template_versions", (string)null);
                });

            modelBuilder.Entity("Prompteer.Domain.Entities.PromptVersionPattern", b =>
                {
                    b.Property<Guid>("PromptTemplateVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArchitecturalPatternId")
                        .HasColumnType("uuid");

                    b.HasKey("PromptTemplateVersionId", "ArchitecturalPatternId");

                    b.HasIndex("ArchitecturalPatternId");

                    b.ToTable("prompt_version_patterns", (string)null);
                });

            modelBuilder.Entity("Prompteer.Domain.Entities.PromptVersionTechnology", b =>
                {
                    b.Property<Guid>("PromptTemplateVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TechnologyId")
                        .HasColumnType("uuid");

                    b.HasKey("PromptTemplateVersionId", "TechnologyId");

                    b.HasIndex("TechnologyId");

                    b.ToTable("prompt_version_technologies", (string)null);
                });

            modelBuilder.Entity("Prompteer.Domain.Entities.Technology", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Ecosystem")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Category", "Ecosystem");

                    b.ToTable("technologies", (string)null);
                });

            modelBuilder.Entity("Prompteer.Domain.Entities.PromptModule", b =>
                {
                    b.HasOne("Prompteer.Domain.Entities.PromptTemplateVersion", "Version")
                        .WithMany("Modules")
                        .HasForeignKey("PromptTemplateVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Version");
                });

            modelBuilder.Entity("Prompteer.Domain.Entities.PromptModuleItem", b =>
                {
                    b.HasOne("Prompteer.Domain.Entities.PromptModule", "Module")
                        .WithMany("Items")
                        .HasForeignKey("PromptModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Prompteer.Domain.Entities.PromptTemplateVersion", b =>
                {
                    b.HasOne("Prompteer.Domain.Entities.PromptTemplate", "Template")
                        .WithMany("Versions")
                        .HasForeignKey("PromptTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Prompteer.Domain.Entities.PromptVersionPattern", b =>
                {
                    b.HasOne("Prompteer.Domain.Entities.ArchitecturalPattern", "Pattern")
                        .WithMany("PromptVersionPatterns")
                        .HasForeignKey("ArchitecturalPatternId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Prompteer.Domain.Entities.PromptTemplateVersion", "Version")
                        .WithMany("Patterns")
                        .HasForeignKey("PromptTemplateVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pattern");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("Prompteer.Domain.Entities.PromptVersionTechnology", b =>
                {
                    b.HasOne("Prompteer.Domain.Entities.PromptTemplateVersion", "Version")
                        .WithMany("Technologies")
                        .HasForeignKey("PromptTemplateVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prompteer.Domain.Entities.Technology", "Technology")
                        .WithMany("PromptVersionTechnologies")
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Technology");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("Prompteer.Domain.Entities.ArchitecturalPattern", b =>
                {
                    b.Navigation("PromptVersionPatterns");
                });

            modelBuilder.Entity("Prompteer.Domain.Entities.PromptModule", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Prompteer.Domain.Entities.PromptTemplate", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Prompteer.Domain.Entities.PromptTemplateVersion", b =>
                {
                    b.Navigation("Modules");

                    b.Navigation("Patterns");

                    b.Navigation("Technologies");
                });

            modelBuilder.Entity("Prompteer.Domain.Entities.Technology", b =>
                {
                    b.Navigation("PromptVersionTechnologies");
                });
#pragma warning restore 612, 618
        }
    }
}
